output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies-logstash"
    document_id => "%{film_id}"
    # Evitar duplicados usando el ID de la película
    doc_as_upsert => true
  }
  
  stdout {
    codec => rubydebug
  }
}
